UPDATED: Makefile, tele.html, logic.js, tele.js, etc...
Added:
- Icons for AppImage (not in dock/panel yet)
- Desktop intergration for AppImage

Fixed:
- Saving telemetry data locally when user doesn't want to deal with any
of it (this does not involve sending the data); Because of how this was
reengineered, all previously collected data is rubbish... but that's not
a problem
- Data being displayed in data sharing window

diff --git a/support/linux/shared-resources/AppRun b/support/linux/shared-resources/AppRun
--- a/support/linux/shared-resources/AppRun
+++ b/support/linux/shared-resources/AppRun
@@ -1,38 +1,223 @@
 #!/bin/bash
 set -e
 
+if [ ! -z "$DEBUG" ] ; then
+  env
+  set -x
+fi
+
+args="$1"
 VENDORPREFIX=appimagekit
 
 THIS="$0"
 
-find-up () {
+function dirResolve () {
   path="$(dirname "$(readlink -f "${THIS}")")"
   while [[ "$path" != "" && ! -e "$path/$1" ]]; do
     path=${path%/*}
   done
 }
 
-if [ -z $APPDIR ] ; then
-  APPDIR=$(find-up "AppRun")
+if [ -z "$APPDIR" ]
+then
+	APPDIR=$(dirResolve "AppRun")
 fi
 
 export PATH="${APPDIR}/usr/bin:${PATH}"
 DESKTOP_FILE="$APPDIR/nz.co.safesurfer.SafeSurferDesktop.desktop"
 BIN="$APPDIR/opt/SafeSurfer-Desktop/SafeSurfer-Desktop"
 
-atexit() {
-if [ -z "$APPIMAGE_EXIT_AFTER_INSTALL" ] ; then
-  if [[ $NUMBER_OF_ARGS -eq 0 ]] ; then
-    exec "$BIN"
-  else
-    exec "$BIN" "${args[@]}"
-  fi
+function atexit() {
+# execute on trap
+if [ -z "$APPIMAGE_EXIT_AFTER_INSTALL" ]
+then
+	if [[ $NUMBER_OF_ARGS -eq 0 ]]
+	then
+		exec "$BIN"
+	else
+		exec "$BIN" "${args[@]}"
+	fi
 fi
 }
 
-if [ ! -f "$DESKTOP_FILE" ] ; then
-  echo "Desktop file is missing. Please run ${THIS} from within an AppImage."
-  exit 0
+function error() {
+# display an error
+if [ -x /usr/bin/zenity ]
+then
+	LD_LIBRARY_PATH="" zenity --error --text "${1}" 2>/dev/null
+elif [ -x /usr/bin/kdialog ]
+then
+	LD_LIBRARY_PATH="" kdialog --msgbox "${1}" 2>/dev/null
+elif [ -x /usr/bin/Xdialog ]
+then
+	LD_LIBRARY_PATH="" Xdialog --msgbox "${1}" 2>/dev/null
+else
+	echo "${1}"
 fi
+exit 1
+}
+
+function yesno() {
+# display a yes or no prompt
+TITLE=$1
+TEXT=$2
+if [ -x /usr/bin/zenity ]
+then
+	LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" --height=250 --width=400 --window-icon="${APPDIR}/ss-logo.png" 2>/dev/null || exit 0
+elif [ -x /usr/bin/kdialog ]
+then
+	LD_LIBRARY_PATH="" kdialog --title "$TITLE" --yesno "$TEXT" || exit 0
+elif [ -x /usr/bin/Xdialog ]
+then
+	LD_LIBRARY_PATH="" Xdialog --title "$TITLE" --clear --yesno "$TEXT" 10 80 || exit 0
+else
+	echo "zenity, kdialog, Xdialog missing. Skipping ${THIS}."
+	exit 0
+fi
+}
+
+function check_prevent() {
+FILE=$1
+if [ -e "$FILE" ]
+then
+	exit 0
+fi
+}
+
+function uninstall_icons() {
+# uninstall previous icons
+for size in 16 24 32 48 64 128 256 512 1024
+do
+	xdg-icon-resource uninstall --noupdate --size "$size" "$VENDORPREFIX-nz.co.safesurfer.SafeSurferDesktop"
+done
+}
+
+case "$args" in
+	--remove-integration)
+		# remove desktop integration
+		set -e
+		uninstall_icons
+		rm -f "$HOME"/.local/share/applications/appimagekit-nz.co.safesurfer.SafeSurferDesktop.desktop
+
+		xdg-desktop-menu forceupdate
+		# for MIME
+		gtk-update-icon-cache
+
+		echo "Integration was successfully removed."
+		exit
+		;;
+	help|--help)
+		echo "Use '--remove-integration' to remove desktop integration."
+		exit
+		;;
+esac
 
 trap atexit EXIT
+
+# Exit immediately of one of these files is present
+# (e.g., because the desktop environment wants to handle desktop integration itself)
+check_prevent "$HOME/.local/share/$VENDORPREFIX/no_desktopintegration"
+check_prevent "/usr/share/$VENDORPREFIX/no_desktopintegration"
+check_prevent "/etc/$VENDORPREFIX/no_desktopintegration"
+
+# Exit immediately if appimaged is running
+pidof appimaged 2>/dev/null && exit 0
+
+# Exit immediately if $DESKTOPINTEGRATION is not empty
+if [ ! -z "$DESKTOPINTEGRATION" ] ; then
+	exit 0
+fi
+
+function check_dep() {
+# check if a given dependency is present
+DEP=$1
+if [ -z "$(which $DEP)" ]
+then
+  	echo "$DEP is missing. Skipping ${THIS}."
+  	exit 0
+fi
+}
+
+# Check whether dependencies are present in base system (we do not bundle these)
+# http://cgit.freedesktop.org/xdg/desktop-file-utils/
+check_dep desktop-file-install
+check_dep xdg-icon-resource
+check_dep xdg-mime
+check_dep xdg-desktop-menu
+
+if [ ! -f "$DESKTOP_FILE" ]
+then
+	echo "Desktop file is missing. Please run ${THIS} from within an AppImage."
+	exit 0
+fi
+
+if [ -z "$APPIMAGE" ]
+then
+	APPIMAGE="$APPDIR/AppRun"
+	# Not running from within an AppImage; hence using the AppRun for Exec=
+fi
+
+# Determine where the desktop file should be installed
+if [[ $EUID -ne 0 ]]; then
+	DESTINATION_DIR_DESKTOP="$HOME/.local/share/applications"
+	SYSTEM_WIDE=""
+else
+	DESTINATION_DIR_DESKTOP="/usr/local/share/applications"
+	# for xdg-mime and xdg-icon-resource
+	SYSTEM_WIDE="--mode system"
+fi
+
+# Check if the desktop file is already there
+# and if so, whether it points to the same AppImage
+if [ -e "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-nz.co.safesurfer.SafeSurferDesktop.desktop" ]
+then
+	INSTALLED_APP_VERSION=$(grep "^X-AppImage-BuildId=" "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-nz.co.safesurfer.SafeSurferDesktop.desktop" | head -n 1 | cut -d " " -f 1)
+	APP_VERSION=$(grep "^X-AppImage-BuildId=" "$DESKTOP_FILE" | head -n 1 | cut -d " " -f 1)
+	echo "installed: $INSTALLED_APP_VERSION image: $APP_VERSION"
+	if [ "$INSTALLED_APP_VERSION" == "$APP_VERSION" ]
+	then
+		exit 0
+	fi
+fi
+
+# we ask the user only if we have found no reason to skip until here
+if [ -z "$APPIMAGE_SILENT_INSTALL" ]
+then
+	yesno "Install" "Would you like to integrate $APPIMAGE with your system?\\n\\nThis will add it to your applications menu and install icons.\\nIf you don't do this you can still launch the application by double-clicking on the AppImage.\\n\\nPlease note you can remove integration by running '$APPIMAGE --remove-integration'"
+fi
+
+# desktop-file-install is supposed to install .desktop files to the user's
+# applications directory when run as a non-root user,
+# and to /usr/share/applications if run as root
+# but that does not really work for me...
+desktop-file-install --rebuild-mime-info-cache \
+	--vendor=$VENDORPREFIX --set-key=Exec --set-value="\"${APPIMAGE}\" %U" \
+	--set-key=X-AppImage-Comment --set-value="Generated by ${THIS}" \
+	--set-icon="ss-logo" --set-key=TryExec --set-value=${APPIMAGE// /\\s} "$DESKTOP_FILE" \
+	--dir "$DESTINATION_DIR_DESKTOP" \
+	--mode=755
+
+uninstall_icons
+
+# Install the icon files for the application
+for size in 16 24 32 48 64 128 256 512 1024
+do
+	xdg-icon-resource install --noupdate --context apps --size "$size" "$APPDIR/usr/share/icons/hicolor/${size}x${size}/apps/ss-logo.png" "$VENDORPREFIX-nz.co.safesurfer.SafeSurferDesktop"
+done
+
+
+
+# force update the icon cache
+xdg-icon-resource forceupdate
+
+# Install the icon files for the mime type; TODO: scalable
+ICONS=$(find "${APPDIR}/usr/share/icons/" -wholename "*/*/*.png" 2>/dev/null || true)
+for ICON in $ICONS
+do
+	ICON_SIZE=$(echo "${ICON}" | rev | cut -d "/" -f 3 | rev | cut -d "x" -f 1)
+	xdg-icon-resource install --context mimetypes --size "${ICON_SIZE}" "${ICON}" $(basename "$ICON" | sed -e 's/.png//g')
+done
+
+xdg-desktop-menu forceupdate
+# for MIME
+gtk-update-icon-cache
