UPDATED: Make file, README.md, TODO.md, menu.js, etc...
Added:
- Dependency checking for Makefile and AppImage
- Feedback paragraph in README.md
- Items to the TODO.md list
- Tool for searching in files (for Bash)
- A user can interface with sscli on a built AppImage--if sscli args are passed to it

Updated:
- Version to 1.0.0b3

Changed:
- If built version is Linux and in an AppImage, then updates will be
enabled

diff --git a/support/linux/shared-resources/sscli b/support/linux/shared-resources/sscli
--- a/support/linux/shared-resources/sscli
+++ b/support/linux/shared-resources/sscli
@@ -48,8 +48,8 @@ enable   enable the DNS
 disable  disable the DNS
 service  check and enable as service
 status	 get the status of the service
-launch   launch the desktop app
 EOF
+[ -z "$ISAPPIMAGE" ] && echo "launch   launch the desktop app"
 }
 
 function enableBackgroundService() {
@@ -157,8 +157,13 @@ case "$arg" in
 		checkServiceState && echo "SERVICE: Enabled." || echo "SERIVCE: Disabled."
 		;;
 	launch|-l|--launch)
-		[[ "$(whoami)" = "root" ]] && echo "ERROR: You can't launch the desktop app as root." && exit 1
-		/opt/SafeSurfer-Desktop/SafeSurfer-Desktop
+		if [ -z "$ISAPPIMAGE" ]
+		then
+			[[ "$(whoami)" = "root" ]] && echo "ERROR: You can't launch the desktop app as root." && exit 1
+			/opt/SafeSurfer-Desktop/SafeSurfer-Desktop
+		else
+			echo "ERROR: you can't launch the app this way from an AppImage."
+		fi
 		;;
 	*)
 		printHelpMenu
